### ISSUE TITLE
Shrine Of Shaping 

### ISSUE THREAD

**Issue by lisa89807** [Priscillalala/ExpansionManager#1]
On the path of the colossus, even if you have seekers of the storm interactables disabled it will still spawn in the shrines of shaping, eating 50 credits for a shrine that does basically nothing. I don't know if the shrines are just dead set on the stages or not but it just feels like even though i have the interactables disabled and it does help by disabling the halyconite shrine, it still keeps the shrine of shaping :/

**Comment by Priscillalala** [comment]
It looks like the Shrine of Shaping has no expansion requirement. This seems like an oversight to me so I added a fix for it. They should stop appearing in v1.0.1. Thank you for noticing this
